=== a-meg-s/XML_Projekt/transport_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:simpleType name="stationName">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Rotkreuz"/>
         <xs:enumeration value="Zurich HB"/>
         <xs:enumeration value="Zug"/>
         <xs:enumeration value="Luzern"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:element name="transportSystem">
      <xs:complexType>
         <xs:sequence>

            <xs:element name="stations">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="station" maxOccurs="unbounded">
                        <xs:complexType>
                           <xs:attribute name="id" type="xs:ID" use="required"/>
                           <xs:attribute name="name" type="stationName" use="required"/>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>

            <xs:element name="timetable">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="connection" maxOccurs="unbounded">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="departure" type="xs:time"/>
                              <xs:element name="arrival" type="xs:time"/>
                              <xs:element name="line" type="xs:string"/>
                              <xs:element name="status" type="xs:string"/>
                           </xs:sequence>
                           <xs:attribute name="id" type="xs:ID" use="required"/>
                           <xs:attribute name="stationRef" type="xs:IDREF"/>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>

            <xs:element name="tariffs">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="ticketType" maxOccurs="unbounded">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="price">
                                 <xs:complexType>
                                    <xs:simpleContent>
                                       <xs:extension base="xs:decimal">
                                          <xs:attribute name="currency" type="xs:string" fixed="CHF"/>
                                       </xs:extension>
                                    </xs:simpleContent>
                                 </xs:complexType>
                              </xs:element>
                              <xs:element name="validity" type="xs:string"/>
                           </xs:sequence>
                           <xs:attribute name="id" type="xs:ID" use="required"/>
                           <xs:attribute name="name" type="xs:string"/>
                           <xs:attribute name="class" type="xs:string"/>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>

         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== a-meg-s/XML_Projekt/transport_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<transportSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="transport_schema.xsd">

   <stations>
      <station id="S01" name="Rotkreuz"/>
      <station id="S02" name="Zurich HB"/>
      <station id="S03" name="Zug"/>
      <station id="S04" name="Luzern"/>
   </stations>

   <timetable>
      <connection id="C101">
         <departure stationRef="S04">14:10:00</departure>
         <arrival stationRef="S02">14:55:00</arrival>
         <line>IR75</line>
         <status>On Time</status>
      </connection>
      <connection id="C102">
         <departure stationRef="S01">08:15:00</departure>
         <arrival stationRef="S03">08:25:00</arrival>
         <line>S1</line>
         <status>Delayed 5 min</status>
      </connection>
   </timetable>

   <tariffs>
      <ticketType id="T01" name="Single Ticket" class="2nd">
         <price currency="CHF">12.60</price>
         <validity>60 min</validity>
      </ticketType>
      <ticketType id="T02" name="Day Pass" class="2nd">
         <price currency="CHF">25.00</price>
         <validity>24 hours</validity>
      </ticketType>
   </tariffs>

</transportSystem>
